language: java
jdk:
  - openjdk7
  - oraclejdk8
notifications:
  email:
    recipients:
          - samgonzul@alum.us.es
                       on_success: never
                       on_failure: never
